---
name: CI🚦

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  rubocop:
    name: 'RuboCop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake rubocop
